format = '${custom.host}${custom.dev}$all'

[custom.host]
command = 'printf HOST'
when = 'test "$DEVCONTAINER_PROMPT_CONTEXT" = HOST'
format = '[$output]($style) '
style = 'bold white bg:red'

[custom.dev]
command = 'printf DEV'
when = 'test "$DEVCONTAINER_PROMPT_CONTEXT" = DEV'
format = '[$output]($style) '
style = 'bold white bg:blue'
