format = '${custom.host}${custom.dev}$all'

[custom.host]
command = 'printf HOST'
when = 'test "$DEVCONTAINER_PROMPT_CONTEXT" = HOST'
symbol = '⚠️'
format = '[ $symbol ](bold white bg:black)[ $output ](bold black bg:yellow) '

[custom.dev]
command = 'printf DEV'
when = 'test "$DEVCONTAINER_PROMPT_CONTEXT" = DEV'
symbol = '🐳'
format = '[ $symbol ](bold white bg:black)[ $output ](bold white bg:blue) '
